//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCFLoggingConfig
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class logconfigEntities : DbContext
    {
        public logconfigEntities()
            : base("name=logconfigEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<sysssislog> sysssislogs { get; set; }
        public virtual DbSet<SSIS_Configuration> SSIS_Configurations { get; set; }
        public virtual DbSet<quickConfiguration> quickConfigurations { get; set; }
    }
}
