//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCFLoggingConfig
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSIS_Configurations
    {
        public string ConfigurationFilter { get; set; }
        public string ConfiguredValue { get; set; }
        public string PackagePath { get; set; }
        public string ConfiguredValueType { get; set; }
    }
}
